### ISSUE TITLE
v1.7 and 1.8-pre use 100% CPU

### ISSUE THREAD

**Issue by JesseBowling** [CommunityHoneyNetwork/dionaea#31]
It appears that when dionaea is run in a container, it will immediately spike to 100% of CPU usage. Using strace on the process reveals that some piece of code fails nearly continuously:

```
epoll_wait(5, [], 64, 0)                = 0
recvfrom(0, 0x7ffddb3f8940, 2048, 0, NULL, NULL) = -1 ENOTSOCK (Socket operation on non-socket)
epoll_wait(5, [], 64, 0)                = 0
recvfrom(0, 0x7ffddb3f8940, 2048, 0, NULL, NULL) = -1 ENOTSOCK (Socket operation on non-socket)
epoll_wait(5, [], 64, 0)                = 0
recvfrom(0, ^C0x7ffddb3f8940, 2048, 0, NULL, NULL) = -1 ENOTSOCK (Socket operation on non-socket)
```
However, giving the container the NET_ADMIN capabilities in docker-compose.yml resolves the issue:

```
version: '2'
services:
  dionaea:
    image: stingar/dionaea:1.8-pre
    volumes:
      - ./dionaea.sysconfig:/etc/default/dionaea:z
      - ./dionaea/dionaea:/etc/dionaea/:z
    ports:
      - "21:21"
      - "23:23"
      - "69:69"
      - "80:80"
      - "123:123"
      - "135:135"
      - "443:443"
      - "445:445"
      - "1433:1433"
      - "1723:1723"
      - "1883:1883"
      - "1900:1900"
      - "3306:3306"
      - "5000:5000"
      - "5060:5060"
      - "5061:5061"
      - "11211:11211"
      - "27017:27017"
    cap_add:
      - NET_ADMIN
```

Ideally it would not be required to give this requirement, as this breaks security boundaries and would make running dionaea incompatible with K8s/OpenShift/etc.
